### PR TITLE
[feat] Add bgp metrics (bgp_session_info)

### PR DESCRIPTION
**Pull request by DrBu7cher**
As described in #547, this PR adds the metrics to monitor the current state of the bgp sessions.

The port of the peer is hard coded, since it is not currently possible to change the port in kube-vip. As soon as this feature is implemented, the port will be accessible by using the peers state, similar to `GetNeighborAddress()`.
If this should be refactored later, just tell me and I append the 179 in the `peerDescription` directly.

Example metrics look like this:
```bash
# HELP bgp_session_info Display state of session by setting metric for label value with current state to 1
# TYPE bgp_session_info gauge
bgp_session_info{peer="123.4.123.4:179",state="ACTIVE"} 0
bgp_session_info{peer="123.4.123.4:179",state="CONNECT"} 0
bgp_session_info{peer="123.4.123.4:179",state="ESTABLISHED"} 1
bgp_session_info{peer="123.4.123.4:179",state="IDLE"} 0
bgp_session_info{peer="123.4.123.4:179",state="OPENCONFIRM"} 0
bgp_session_info{peer="123.4.123.4:179",state="OPENSENT"} 0
bgp_session_info{peer="123.4.123.4:179",state="UNKNOWN"} 0
bgp_session_info{peer="123.4.123.5:179",state="ACTIVE"} 0
bgp_session_info{peer="123.4.123.5:179",state="CONNECT"} 0
bgp_session_info{peer="123.4.123.5:179",state="ESTABLISHED"} 1
bgp_session_info{peer="123.4.123.5:179",state="IDLE"} 0
bgp_session_info{peer="123.4.123.5:179",state="OPENCONFIRM"} 0
bgp_session_info{peer="123.4.123.5:179",state="OPENSENT"} 0
bgp_session_info{peer="123.4.123.5:179",state="UNKNOWN"} 0
```

### CODE REVIEW

**Comment by thebsdbox** [comment]
This is excellent ! (Thankyou ! )

**Comment by DrBu7cher** [comment]
Regarding the failing check: Is this something I broke? I think I didn't even touch these files...so I guess not?
Please let me know.

**Comment by DrBu7cher** [comment]
I think #557 should fix this, right? :)

**Review by thebsdbox — APPROVED** [review]
`/LGTM`

**Pull request merged**
