### PR TITLE
Remove pkg/service and address items flagged by linting

### LINKED ISSUE #548: Remove pkg/service
**Is your feature request related to a problem? Please describe.**
`pkg/service` it's no longer maintained

**Describe the solution you'd like**
We're going to remove it to simplify the code base

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by sykesm**
Fixes #548

### CODE REVIEW

**Comment by thebsdbox** [comment]
oh wow!

**Review by thebsdbox — APPROVED** [review]
This is excellent.. :-D

**Comment by thebsdbox** [comment]
Apologies @sykesm I merged these in the wrong order, are you ok to fix the merge commits (some of `/pkg/service` is re-added)

**Comment by sykesm** [comment]
> Awesome, is this ready to go?

Should be. It was pretty straightforward.

**Pull request merged**
