### PR TITLE
Mirror traffic of service interface to a dest interface

### PR DESCRIPTION
**Pull request by lubronzhan**
Fix https://github.com/kube-vip/kube-vip/issues/589

Introduce a new env variable `mirror_dest_interface`, the user could set it to an second interface other than the service interface or default interface. Then all traffic of service that goes to the default interface or service interface will also be mirrored to the dest interface

Idea from https://gist.github.com/mcastelino/7d85f4164ffdaf48242f9281bb1d0f9b

### CODE REVIEW

**Comment by thebsdbox** [comment]
Looks good, at the moment this is only implemented to "routing table mode". Will it be added for ARP and BGP?

**Comment by lubronzhan** [comment]
Yeah thanks for reminding, I moved it to servicesWatcher so it will be triggered on all modes if enabled.

I'll also try validate it in environment first

**Comment by lubronzhan** [comment]
Verified on a real env now
```
root@wl-antrea-controlplane-2864w-vr78p:/home/capv# sudo tc filter show dev eth0
filter parent 1: protocol ip pref 1 u32 chain 0
filter parent 1: protocol ip pref 1 u32 chain 0 fh 800: ht divisor 1
filter parent 1: protocol ip pref 1 u32 chain 0 fh 800::800 order 2048 key ht 800 bkt 0 flowid 1:1 not_in_hw
  match 094c0000/ffff0000 at 20
filter parent 1: protocol ip pref 1 u32 chain 0 fh 800::801 order 2049 key ht 800 bkt 0 flowid 1:1 not_in_hw
  match 0000094c/0000ffff at 20
filter parent 1: protocol ip pref 2 u32 chain 0
filter parent 1: protocol ip pref 2 u32 chain 0 fh 801: ht divisor 1
filter parent 1: protocol ip pref 2 u32 chain 0 fh 801::800 order 2048 key ht 801 bkt 0 flowid 1:1 not_in_hw
  match 094b0000/ffff0000 at 20
filter parent 1: protocol ip pref 2 u32 chain 0 fh 801::801 order 2049 key ht 801 bkt 0 flowid 1:1 not_in_hw
  match 0000094b/0000ffff at 20
filter parent 1: protocol all pref 49152 u32 chain 0
filter parent 1: protocol all pref 49152 u32 chain 0 fh 802: ht divisor 1
filter parent 1: protocol all pref 49152 u32 chain 0 fh 802::800 order 2048 key ht 802 bkt 0 terminal flowid ??? not_in_hw
  match 00000000/00000000 at 0
	action order 1: mirred (Egress Mirror to device eth1) pipe
	index 2 ref 1 bind 1

root@wl-antrea-controlplane-2864w-vr78p:/home/capv# sudo tc qdisc show dev eth0
qdisc prio 1: root refcnt 3 bands 3 priomap 1 2 2 2 1 2 0 0 1 1 1 1 1 1 1 1
qdisc ingress ffff: parent ffff:fff1 ----------------
```

But also found a bug that if the container is killed accidently, then the qdisc was left over, then kube-vip can't start up. I need to fix the logic to clean up the remaining qdisc before starting
```
I0227 01:45:29.725243       1 leaderelection.go:250] attempting to acquire leader lease kube-system/plndr-cp-lock...
I0227 01:45:29.757027       1 leaderelection.go:260] successfully acquired lease kube-system/plndr-svcs-lock
time="2024-02-27T01:45:29Z" level=info msg="mirroring traffic from interface eth0 to interface eth1"
time="2024-02-27T01:45:29Z" level=debug msg="interface eth0 has index 2\n"
time="2024-02-27T01:45:29Z" level=debug msg="interface eth1 has index 12\n"
time="2024-02-27T01:45:29Z" level=debug msg="step 1: tc qdisc add dev eth0 ingress\n"
time="2024-02-27T01:45:29Z" level=error msg="failed to add qdisc for index 2 : file exists"
I0227 01:45:29.760585       1 leaderelection.go:260] successfully acquired lease kube-system/plndr-cp-lock
time="2024-02-27T01:45:29Z" level=info msg="Node [wl-antrea-controlplane-2864w-vr78p] is assuming leadership of the cluster"
time="2024-02-27T01:45:29Z" level=info msg="Gratuitous Arp broadcast will repeat every 3 seconds for [10.215.34.56]"
```

Also the service controller can't start either. 

Hi @thebsdbox do you think it make more sense to return fatal [here](https://github.com/kube-vip/kube-vip/blob/main/pkg/manager/manager_wireguard.go#L118)/[here](https://github.com/kube-vip/kube-vip/blob/main/pkg/manager/manager_arp.go#L160)/[here](https://github.com/kube-vip/kube-vip/blob/main/pkg/manager/manager_table.go#L98) so kube-vip could crash and restart so that it can inform the user that service watcher is not running. Instead of letting it running silently without letting customer know that the watcher is not actually running

**Comment by thebsdbox** [comment]
Good question, it either logs errors and services stay in `pending` or the pod itself goes into `crashLoopBack` etc..

I think it might be best moving it to `fatal`.

**Comment by thebsdbox** [comment]
Other than the few nits, I'm loving the new feature!

**Review by thebsdbox — APPROVED** [review]

**Comment by thebsdbox** [comment]
Is this ready to merge?

**Comment by lubronzhan** [comment]
Yes it's ready now. I don't see the merge button though

**Comment by lubronzhan** [comment]
I'll check if it's testable inside kind node by adding a different interface and create another pr for e2e if that's doable

Looks like it's doable https://gist.github.com/aojea/00bca6390f5f67c0a30db6acacf3ea91

**Comment by thebsdbox** [comment]
> Yes it's ready now. I don't see the merge button though

Big feature, it’s going to be merged into a v0.8.0

**Comment by thebsdbox** [comment]
Going to merge this and quickly fix the linting afterwards. !

**Pull request merged**
