### PR TITLE
Set api-endpoint to host for incluster deployment

### PR DESCRIPTION
**Pull request by AxiomSamarth**
This PR is a proposed fix for issue #394

### CODE REVIEW

**Comment by thebsdbox** [comment]
Ah cool, thanks for the PR! testing now :D

**Review by thebsdbox — APPROVED** [review]
`/lgtm`

**Comment by AxiomSamarth** [comment]
Thank you so much for the lightning-fast review & merge, @thebsdbox ! ❤️

**Comment by AxiomSamarth** [comment]
@thebsdbox How should the pod manifest look like with `inCluster` set to true? Somehow, my static pod does not seem to start.

```
spec:
  containers:
  - args:
    - start     
    - --inCluster=true
```

Is this how it should look like or should the manifest have the flag `--inCluster` supplied in a different way?

**Comment by thebsdbox** [comment]
```
export KVVERSION=v0.4.4
alias kube-vip="docker run --network host --rm ghcr.io/kube-vip/kube-vip:$KVVERSION"
kube-vip manifest daemonset     --interface $INTERFACE    --inCluster    <other flags>
```

**Comment by thebsdbox** [comment]
A new release tagged `main` should appear soon with your code changes in it.

**Comment by ggaurav10** [comment]
@AxiomSamarth @thebsdbox do we need to handle the following case too - `if len(path) == 0 && inCluster`?
Also, should we use `hostname = os.Hostname():port` instead of `hostname = kubernetes:port`? This way we wouldn't break existing use cases where pod spec isn't using the following field:
```
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
```

wdyt?

**Comment by ggaurav10** [comment]
@AxiomSamarth @thebsdbox do we need to handle the following case too - `if len(path) == 0 && inCluster` by setting `path = filepath.Join(os.Getenv("HOME"), ".kube", "config")`?
Also, should we use `hostname = os.Hostname():port` instead of `hostname = kubernetes:port`? This way we wouldn't break existing use cases where pod spec isn't using the following field:
```
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
```

wdyt?

**Comment by AxiomSamarth** [comment]
@thebsdbox I think, the if condition to check if the `inCluster` flag is set is not needed [here](https://github.com/kube-vip/kube-vip/blob/b9014ae32a180620bd61e3f6c8b03c45147adaae/pkg/cluster/clusterLeaderElection.go#L50-L52). 

We can have the `hostname = fmt.Sprintf("kubernetes:%v", port)` as default which gets updated to `hostname = fmt.Sprintf("%s:%v", id, port)` it it is out-of-cluster [here](https://github.com/kube-vip/kube-vip/blob/b9014ae32a180620bd61e3f6c8b03c45147adaae/pkg/cluster/clusterLeaderElection.go#L53-L62).

This way, user will also not have to undergo the process of setting up `serviceaccounttoken`, `ca.crt`,  `KUBERNETES_SERVICE_HOST `& `KUBERNETES_SERVICE_PORT ` to generate the `clientSet` when `inCluster` flag is set. 

WDYT?

**Pull request merged**
