### PR TITLE
Deprecate loadbalancerIP, use annotation to fetch service loadbalancerIP

### PR DESCRIPTION
**Pull request by lubronzhan**
Fix #https://github.com/kube-vip/kube-vip/issues/457
PR in website: https://github.com/kube-vip/website/pull/15
Related issue in kube-vip-cloud-provider https://github.com/kube-vip/kube-vip-cloud-provider/issues/51
* Add new annotation `kube-vip.io/loadbalancerIPs` to specify the loadbalancer ip for service 
* Now ip address fetched from loadbalancer service are first fetched from annotation, then fallback to service spec 
* Unit test

### CODE REVIEW

**Comment by thebsdbox** [comment]
Apologies... All documentation for kube-vip.io lives in the /website repo.

**Comment by lubronzhan** [comment]
Ohk, let me also create PR there

**Comment by lubronzhan** [comment]
Should I only update the website repo or both?

**Comment by lubronzhan** [comment]
Follow up PR here https://github.com/kube-vip/website/pull/15
I think I need to update the pr in website again once the release 0.5.12 is cut so they know which version they should start using the annotations

**Pull request merged**
