### PR TITLE
fix: Using log instead of fmt.print

### PR DESCRIPTION
**Pull request by ii2day**
When I was looking at the source code, I noticed that print was being used here, and I felt it would be better to change it to log output.

### CODE REVIEW

**Comment by lubronzhan** [comment]
Good find. Would you mind also finding and fixing other places using fmt to print log?

On a brief search I find blow places as well

https://github.com/kube-vip/kube-vip/blob/34a4352faed124d7d8a0f6af5f352b77146974b3/cmd/kube-vip.go#L172
https://github.com/kube-vip/kube-vip/blob/34a4352faed124d7d8a0f6af5f352b77146974b3/cmd/kube-vip-manifests.go#L57
https://github.com/kube-vip/kube-vip/blob/34a4352faed124d7d8a0f6af5f352b77146974b3/cmd/kube-vip-kubeadm.go#L57

Thank you

**Comment by ii2day** [comment]
> Good find. Would you mind also finding and fixing other places using fmt to print log?
> 
> On a brief search I find blow places as well
> 
> https://github.com/kube-vip/kube-vip/blob/34a4352faed124d7d8a0f6af5f352b77146974b3/cmd/kube-vip.go#L172
> 
> 
> https://github.com/kube-vip/kube-vip/blob/34a4352faed124d7d8a0f6af5f352b77146974b3/cmd/kube-vip-manifests.go#L57
> 
> 
> https://github.com/kube-vip/kube-vip/blob/34a4352faed124d7d8a0f6af5f352b77146974b3/cmd/kube-vip-kubeadm.go#L57
> 
> Thank you

Okay, I've searched globally and changed the place for fmt.print to log

**Comment by lubronzhan** [comment]
Thanks. Dan should have the permission to start the test

/ok-to-test

**Comment by thebsdbox** [comment]
Nice, once this goes through we should be pretty much ready to do the new release

**Comment by ii2day** [comment]
> Nice, once this goes through we should be pretty much ready to do the new release

🎉 By the way, I've noticed that kube-vip's logging doesn't output the number of log lines, which is annoying for people who aren't familiar with kube-vip's code. Is it considered to improve this log output?

**Pull request merged**
