### PR TITLE
Add support for ppc64le architecture

### PR DESCRIPTION
**Pull request by mkumatag**
This PR for adding support for the linux/ppc64le architecture support

### CODE REVIEW

**Comment by mkumatag** [comment]
cc @thebsdbox

**Comment by thebsdbox** [comment]
Kicked off the workflow!

**Comment by mkumatag** [comment]
> Kicked off the workflow!

workflow passed :)

**Comment by thebsdbox** [comment]
Awesome thanks!

**Comment by mkumatag** [comment]
Can we have a release with this fix?

**Comment by thebsdbox** [comment]
Yes, i'm just on a hackathon at the moment :-) I'll drop 0.3.7 this
afternoon!

**Comment by thebsdbox** [comment]
New release is being built now.

**Pull request merged**
