### PR TITLE
Extensive linting, corrections, expansions

### PR DESCRIPTION
**Pull request by chipzoller**
Signed-off-by: Chip Zoller <chipzoller@gmail.com>

This PR attempts to improve on the following areas:

* Perform best-effort Markdown linting without terribly impacting too many visible elements.
* Misc. spelling corrections, styling (Kubernetes resources are treated as proper nouns; the project title "kube-vip" is beginning to be standardized in code), and formatting
* Clarification and expansion targeted primarily at the home page, static manifest generation with ARP workflow, and on-prem section featuring cloud controller documentation.

Questions for maintainers:

~1. In the on-prem page, there is/was a broken link to a `#flow` anchor. Unsure where this pointed so it was removed. Noticed an `overview.png` file in root but, again, unsure. Which is correct here?~
~2. Also in the root is a Markdown file `kubernetes-control-plane.md`. Should this be cleaned up?~
~3. `/flags` states "VIP addresses can be both IPv4 or IPv6". Is it "both" (AND) or is it "or"?~

### CODE REVIEW

**Comment by thebsdbox** [comment]
Awesome, this is excellent!

**Comment by thebsdbox** [comment]
1. it's old content that can probably be removed
2. This can be removed
3. It's either.. the code will identify the INET type and will follow the correct path.

**Comment by chipzoller** [comment]
> 1. it's old content that can probably be removed
> 
>     2. This can be removed
> 
>     3. It's either.. the code will identify the INET type and will follow the correct path.

Fixed

**Comment by thebsdbox** [comment]
Awesome, i'd love to get this merged and then add in this IPVS fix for a new release 👍

**Review by thebsdbox — APPROVED** [review]
Excellent stuff !

**Comment by chipzoller** [comment]
@thebsdbox I am at a decent stopping point for right now. Included revamping of the K3s page and other updates. I realize this is extensive and if you/maintainers would rather not accept but cherry pick from what I've provided, you're welcome to close this PR and do so.

**Review by thebsdbox — APPROVED** [review]

**Pull request merged**
