### PR TITLE
fix: Modify the ImagePullPolicy used by cli manifest

### PR DESCRIPTION
**Pull request by Bao0ne**
#804

### CODE REVIEW

**Review by lubronzhan — CHANGES_REQUESTED** [review]
Could you also change here? https://github.com/kube-vip/kube-vip/blob/f1cf044eae1edcb016b3aab10480038c423a0fdb/testing/e2e/services/kubernetes.go#L152

**Comment by Bao0ne** [comment]
> Could you also change here?
> 
> https://github.com/kube-vip/kube-vip/blob/f1cf044eae1edcb016b3aab10480038c423a0fdb/testing/e2e/services/kubernetes.go#L152

Sure

**Review by lubronzhan — APPROVED** [review]
LGMT. Just need Dan's approval

**Comment by Cellebyte** [comment]
LGTM,

thanks for the contribution.

**Pull request merged**
