### PR TITLE
fix ddns support

### PR DESCRIPTION
**Pull request by sadysnaat**
Fixes: #328

### CODE REVIEW

**Review by thebsdbox — CHANGES_REQUESTED** [review]
Looks like it fixes an introduced bug, can we get a little bit of information?

**Comment by thebsdbox** [comment]
I'm probably going to merge this sooner rather than later as I'd like to cut a new release.. but a note would be helpful @sadysnaat :-D

**Comment by sadysnaat** [comment]
> I'm probably going to merge this sooner rather than later as I'd like to cut a new release.. but a note would be helpful @sadysnaat :-D

@thebsdbox Issue logged at #328

**Review by thebsdbox — APPROVED** [review]
AWESOME Thanks !

**Pull request merged**
