### PR TITLE
feat: push images to ghcr

### PR DESCRIPTION
**Pull request by onedr0p**
Fixes: https://github.com/kube-vip/kube-vip/issues/211

### CODE REVIEW

**Comment by thebsdbox** [comment]
Oh nice!!!

I'm on PTO so will enable this on Monday 😀

**Comment by onedr0p** [comment]
Sure, enjoy!

**Comment by ibotty** [comment]
It's still not accessible afaict.

**Comment by onedr0p** [comment]
Seems like we're awaiting a new release.

**Comment by onedr0p** [comment]
According to https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

> To use the Container registry, you must enable the feature preview.

**Pull request merged**
